"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { unidadeDoUsuario } from "@/lib/unidades/guard";
import type { ChecklistTemplate, Recorrencia, TarefaTemplate } from "@/types/database";
const recorrencias: Recorrencia[] = ["diaria", "semanal", "mensal"];
const listaPath = (u: string) => `/unidades/${u}/checklists`;
const itemPath = (u: string, c: string) => `${listaPath(u)}/${c}`;
export async function listarChecklists(unidadeId: string) { const { data } = await createClient().from("checklist_templates").select("*").eq("unidade_id", unidadeId).order("nome"); return (data ?? []) as ChecklistTemplate[]; }
export async function buscarChecklist(unidadeId: string, checklistId: string) { const supabase = createClient(); const { data: checklist } = await supabase.from("checklist_templates").select("*").eq("id", checklistId).eq("unidade_id", unidadeId).maybeSingle(); if (!checklist) return null; const { data: tarefas } = await supabase.from("tarefa_templates").select("*").eq("checklist_template_id", checklistId).order("ordem"); return { checklist: checklist as ChecklistTemplate, tarefas: (tarefas ?? []) as TarefaTemplate[] }; }
async function campos(unidadeId: string, formData: FormData) { const nome = String(formData.get("nome") ?? "").trim(); const setor_id = String(formData.get("setor_id") ?? "").trim(); const responsavel_id = String(formData.get("responsavel_id") ?? "").trim(); const recorrencia = String(formData.get("recorrencia") ?? "") as Recorrencia; const horario = String(formData.get("horario") ?? "").trim(); if (!nome || !setor_id || !responsavel_id || !horario || !recorrencias.includes(recorrencia)) return { ok: false as const, erro: "Preencha nome, setor, responsável, frequência e horário." }; const { data: setor } = await createClient().from("setores").select("id").eq("id", setor_id).eq("unidade_id", unidadeId).maybeSingle(); if (!setor) return { ok: false as const, erro: "Setor inválido para esta unidade." }; return { ok: true as const, valores: { nome, setor_id, responsavel_id, recorrencia, horario, descricao: String(formData.get("descricao") ?? "").trim() || null } }; }
export async function criarChecklist(unidadeId: string, formData: FormData) { const contexto = await unidadeDoUsuario(unidadeId); if (!contexto || contexto.usuario.perfil !== "gestor") redirect(`${listaPath(unidadeId)}/novo?erro=Sem%20permiss%C3%A3o`); const validacao = await campos(unidadeId, formData); if (!validacao.ok) redirect(`${listaPath(unidadeId)}/novo?erro=${encodeURIComponent(validacao.erro)}`); const { data } = await createClient().from("checklist_templates").insert({ unidade_id: unidadeId, ...validacao.valores }).select("id").single(); if (!data) redirect(`${listaPath(unidadeId)}/novo?erro=Não%20foi%20possível%20criar`); revalidatePath(listaPath(unidadeId)); redirect(`${itemPath(unidadeId, data.id)}?novaTarefa=1&sucesso=1`); }
export async function atualizarChecklist(unidadeId: string, checklistId: string, formData: FormData) { const contexto = await unidadeDoUsuario(unidadeId); if (!contexto || contexto.usuario.perfil !== "gestor") redirect(itemPath(unidadeId, checklistId)); const validacao = await campos(unidadeId, formData); if (!validacao.ok) redirect(`${itemPath(unidadeId, checklistId)}?erro=${encodeURIComponent(validacao.erro)}`); await createClient().from("checklist_templates").update(validacao.valores).eq("id", checklistId).eq("unidade_id", unidadeId); revalidatePath(itemPath(unidadeId, checklistId)); revalidatePath(listaPath(unidadeId)); redirect(`${listaPath(unidadeId)}?sucesso=1`); }
export async function alternarStatusChecklist(unidadeId: string, checklistId: string, ativo: boolean, _formData: FormData) { const contexto = await unidadeDoUsuario(unidadeId); if (!contexto || contexto.usuario.perfil !== "gestor") return; await createClient().from("checklist_templates").update({ ativo }).eq("id", checklistId).eq("unidade_id", unidadeId); revalidatePath(listaPath(unidadeId)); revalidatePath(itemPath(unidadeId, checklistId)); }
export async function duplicarChecklist(unidadeId: string, checklistId: string, _formData: FormData) { const contexto = await unidadeDoUsuario(unidadeId); if (!contexto || contexto.usuario.perfil !== "gestor") return; const original = await buscarChecklist(unidadeId, checklistId); if (!original) return; const supabase = createClient(); const { data: copia } = await supabase.from("checklist_templates").insert({ unidade_id: unidadeId, setor_id: original.checklist.setor_id, responsavel_id: original.checklist.responsavel_id, nome: `${original.checklist.nome} - Cópia`, descricao: original.checklist.descricao, recorrencia: original.checklist.recorrencia, horario: original.checklist.horario, ativo: true }).select("id").single(); if (!copia) return; if (original.tarefas.length) await supabase.from("tarefa_templates").insert(original.tarefas.map((t) => ({ checklist_template_id: copia.id, titulo: t.titulo, tipo: t.tipo, obrigatoria: t.obrigatoria, ordem: t.ordem }))); revalidatePath(listaPath(unidadeId)); redirect(itemPath(unidadeId, copia.id)); }