"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { unidadeDoUsuario } from "@/lib/unidades/guard";
import type { TarefaTemplate, TipoTarefa } from "@/types/database";
const tipos: TipoTarefa[] = ["checkbox", "sim_nao", "numero", "texto"];
const path = (u: string, c: string) => `/unidades/${u}/checklists/${c}`;
async function autorizado(u: string, c: string) { const contexto = await unidadeDoUsuario(u); if (!contexto || contexto.usuario.perfil !== "gestor") return null; const { data } = await createClient().from("checklist_templates").select("id").eq("id", c).eq("unidade_id", u).maybeSingle(); return data; }
async function criarTarefaUnica(u: string, c: string, formData: FormData) { if (!await autorizado(u, c)) redirect(path(u, c)); const titulo = String(formData.get("titulo") ?? "").trim(); const tipo = String(formData.get("tipo") ?? "checkbox") as TipoTarefa; if (!titulo || !tipos.includes(tipo)) redirect(`${path(u, c)}?novaTarefa=1&erro=Informe%20o%20título%20e%20o%20tipo`); const supabase = createClient(); const { data: ultima } = await supabase.from("tarefa_templates").select("ordem").eq("checklist_template_id", c).order("ordem", { ascending: false }).limit(1).maybeSingle(); await supabase.from("tarefa_templates").insert({ checklist_template_id: c, titulo, tipo, obrigatoria: formData.get("obrigatoria") === "on", ordem: (ultima?.ordem ?? -1) + 1 }); revalidatePath(path(u, c)); redirect(path(u, c)); }
export async function criarTarefas(u: string, c: string, formData: FormData) { if (!await autorizado(u, c)) redirect(path(u, c)); const titulos = formData.getAll("titulo").map((value) => String(value).trim()); const tiposEnviados = formData.getAll("tipo").map((value) => String(value) as TipoTarefa); if (!titulos.length || titulos.some((titulo, index) => !titulo || !tipos.includes(tiposEnviados[index]))) redirect(`${path(u, c)}?novaTarefa=1&erro=Preencha%20todas%20as%20tarefas`); const supabase = createClient(); const { data: ultima } = await supabase.from("tarefa_templates").select("ordem").eq("checklist_template_id", c).order("ordem", { ascending: false }).limit(1).maybeSingle(); const ordemInicial = (ultima?.ordem ?? -1) + 1; const { error } = await supabase.from("tarefa_templates").insert(titulos.map((titulo, index) => ({ checklist_template_id: c, titulo, tipo: tiposEnviados[index], obrigatoria: formData.get(`obrigatoria-${index}`) === "on", ordem: ordemInicial + index }))); if (error) redirect(`${path(u, c)}?novaTarefa=1&erro=Não%20foi%20possível%20salvar%20as%20tarefas`); revalidatePath(path(u, c)); redirect(path(u, c)); }
export const criarTarefa = criarTarefas;
export async function atualizarTarefa(u: string, c: string, id: string, formData: FormData) { if (!await autorizado(u, c)) redirect(path(u, c)); const titulo = String(formData.get("titulo") ?? "").trim(); const tipo = String(formData.get("tipo") ?? "checkbox") as TipoTarefa; if (!titulo || !tipos.includes(tipo)) redirect(`${path(u, c)}?editarTarefa=${id}&erro=Informe%20o%20título%20e%20o%20tipo`); await createClient().from("tarefa_templates").update({ titulo, tipo, obrigatoria: formData.get("obrigatoria") === "on" }).eq("id", id).eq("checklist_template_id", c); revalidatePath(path(u, c)); redirect(path(u, c)); }
export async function excluirTarefa(u: string, c: string, id: string, _formData: FormData) { if (!await autorizado(u, c)) redirect(path(u, c)); await createClient().from("tarefa_templates").delete().eq("id", id).eq("checklist_template_id", c); revalidatePath(path(u, c)); redirect(path(u, c)); }
export async function moverTarefa(u: string, c: string, id: string, direcao: "cima" | "baixo", _formData: FormData) { if (!await autorizado(u, c)) return; const supabase = createClient(); const { data } = await supabase.from("tarefa_templates").select("*").eq("checklist_template_id", c).order("ordem"); const tarefas = (data ?? []) as TarefaTemplate[]; const i = tarefas.findIndex((t) => t.id === id); const j = direcao === "cima" ? i - 1 : i + 1; if (i < 0 || j < 0 || j >= tarefas.length) return; await supabase.from("tarefa_templates").update({ ordem: tarefas[j].ordem }).eq("id", tarefas[i].id); await supabase.from("tarefa_templates").update({ ordem: tarefas[i].ordem }).eq("id", tarefas[j].id); revalidatePath(path(u, c)); }